server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://192.168.1.213:3306/mmall_learning?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
mybatis:
    mapper-locations: classpath:mapping/*.xml
logging:
  file: myapp.log
  config: classpath:logbackProd-spring.xml
  path: ./logs
  level:
    com.mmall.dao: debug