package com.mmall.dao;

import com.mmall.domain.Cart;
import com.mmall.domain.CartCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int countByExample(CartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByExample(CartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Cart> selectByExampleWithRowbounds(CartCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Cart> selectByExample(CartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExample(@Param("record") Cart record, @Param("example") CartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKey(Cart record);
}