package com.mmall.dao;

import com.mmall.domain.Category;
import com.mmall.domain.CategoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int countByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Category> selectByExampleWithRowbounds(CategoryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Category> selectByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKey(Category record);
}