package com.mmall.dao;

import com.mmall.domain.MmallUser;
import com.mmall.domain.MmallUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MmallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int countByExample(MmallUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByExample(MmallUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insert(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insertSelective(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallUser> selectByExampleWithRowbounds(MmallUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallUser> selectByExample(MmallUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    MmallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") MmallUser record, @Param("example") MmallUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExample(@Param("record") MmallUser record, @Param("example") MmallUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(MmallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKey(MmallUser record);
}