package com.mmall.dao;

import com.mmall.domain.MmallOrderItem;
import com.mmall.domain.MmallOrderItemCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MmallOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int countByExample(MmallOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByExample(MmallOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insert(MmallOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insertSelective(MmallOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallOrderItem> selectByExampleWithRowbounds(MmallOrderItemCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallOrderItem> selectByExample(MmallOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    MmallOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") MmallOrderItem record, @Param("example") MmallOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExample(@Param("record") MmallOrderItem record, @Param("example") MmallOrderItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(MmallOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKey(MmallOrderItem record);
}