package com.mmall.dao;

import com.mmall.domain.MmallCart;
import com.mmall.domain.MmallCartCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MmallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int countByExample(MmallCartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByExample(MmallCartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insert(MmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insertSelective(MmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallCart> selectByExampleWithRowbounds(MmallCartCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallCart> selectByExample(MmallCartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    MmallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") MmallCart record, @Param("example") MmallCartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExample(@Param("record") MmallCart record, @Param("example") MmallCartCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(MmallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKey(MmallCart record);
}