package com.mmall.dao;

import com.mmall.domain.MmallOrder;
import com.mmall.domain.MmallOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int countByExample(MmallOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByExample(MmallOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insert(MmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int insertSelective(MmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallOrder> selectByExampleWithRowbounds(MmallOrderCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    List<MmallOrder> selectByExample(MmallOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    MmallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") MmallOrder record, @Param("example") MmallOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByExample(@Param("record") MmallOrder record, @Param("example") MmallOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKeySelective(MmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated Sun Apr 08 16:54:27 CST 2018
     */
    int updateByPrimaryKey(MmallOrder record);
}