package com.mmall.dao;

import com.mmall.domain.Order;
import com.mmall.domain.OrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int countByExample(OrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByExample(OrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Order> selectByExampleWithRowbounds(OrderCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Order> selectByExample(OrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKey(Order record);
}