package com.mmall.dao;

import com.mmall.domain.PayInfo;
import com.mmall.domain.PayInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int countByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<PayInfo> selectByExampleWithRowbounds(PayInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<PayInfo> selectByExample(PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") PayInfo record, @Param("example") PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExample(@Param("record") PayInfo record, @Param("example") PayInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_info
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKey(PayInfo record);
}