package com.mmall.dao;

import com.mmall.domain.Shipping;
import com.mmall.domain.ShippingCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int countByExample(ShippingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByExample(ShippingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Shipping> selectByExampleWithRowbounds(ShippingCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    List<Shipping> selectByExample(ShippingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shipping record, @Param("example") ShippingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByExample(@Param("record") Shipping record, @Param("example") ShippingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbggenerated Mon Apr 09 11:26:14 CST 2018
     */
    int updateByPrimaryKey(Shipping record);
}